### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RamonSmit** [Sumukh/dokku-sentry#1]
Are you're going to keep this up-2-date ish? I want to use this for my personal production projects. 
and don't really want the hassle to switch around. 

Cheers,
Ramon

**Comment by Sumukh** [comment]
Probably not to Sentry 9+ - happy to accept PRs though. This should be a good starting point for sentry installations

Something that might be worth looking into ishttps://github.com/getsentry/docker-sentry

**Comment by RamonSmit** [comment]
I will take a look into the repos. I really would like some stable updatable stuff. I'm going to sneekpeak inside here and there for more info. 

Thanks!
